import { BaseAgent, AgentOutput } from './BaseAgent';
import { AgentContext } from '../behavioral/AgentOutputFilter';
import * as fs from 'fs';
import * as path from 'path';

export class ProjectManagerAgent extends BaseAgent {
    public readonly role = 'project-manager';
    private projectRoot = process.cwd();

    protected async generateResponse(input: string, context: AgentContext): Promise<AgentOutput> {

        // PM specific capabilities triggered by context phase
        if (context['phase'] === '1A') {
            this.generateNEXUSmd();
            this.generateFASmd();
        }

        if (context['phase'] === '12') {
            this.synthesizeMaintenance();
        }

        return {
            agentRole: this.role,
            phase: context['phase'] || 'UNKNOWN',
            content: `[PM] Processing input: ${input.substring(0, 30)}...`,
        };
    }

    public generateNEXUSmd(): void {
        const nexusMdPath = path.join(this.projectRoot, 'NEXUS.md');
        const content = `# NEXUS.md — Project Overview
# Generated by NEXUS AI Project Manager — Phase 1A
# Updated automatically at every completed phase

## Module Classification — from verify_project.py
| Category  | Definition                                                      |
|-----------|----------------------------------------------------------------|
| WIRED     | In transitive import graph of ENTRY_POINT                      |
| NOT_WIRED | Exists on disk but never imported by entry point               |
| TEST      | Test file — excluded from wiring check                         |
| CONFIG    | Config/init file — excluded from wiring check                  |

## Exit Codes
| Code | Meaning                                    |
|------|--------------------------------------------|
| 0    | All CRITICAL_MODULES are WIRED             |
| 1    | One or more CRITICAL_MODULES are NOT_WIRED |

## Mandatory Rules for All Agents
1. Any module written = immediately WIRED + verify_project.py run
2. verify_project.py runs BEFORE any progress report
3. Agent cannot report phase complete if exit code != 0
4. 'Ran' != 'Worked correctly' — report both
5. Zero silent failures — any drop/skip/ignore = log entry
6. NOT_WIRED modules are dead code — they do not count as delivered
`;
        fs.writeFileSync(nexusMdPath, content, 'utf8');
        console.log(`[PM] Generated NEXUS.md at ${nexusMdPath}`);
    }

    public generateFASmd(): void {
        const docsDir = path.join(this.projectRoot, '.nexus', 'docs');
        if (!fs.existsSync(docsDir)) fs.mkdirSync(docsDir, { recursive: true });

        const fasPath = path.join(docsDir, 'FAS.md');
        const content = `# Functional Architecture Sheet (FAS)
// Generated by PM Agent 
// Every OPEN function MUST have a CLOSE function.
`;
        fs.writeFileSync(fasPath, content, 'utf8');
        console.log(`[PM] Generated FAS.md at ${fasPath}`);
    }

    public synthesizeMaintenance(): void {
        const docsDir = path.join(this.projectRoot, '.nexus', 'docs');
        if (!fs.existsSync(docsDir)) fs.mkdirSync(docsDir, { recursive: true });

        const maintPath = path.join(docsDir, 'MAINTENANCE_GUIDE.md');
        const content = `# Maintenance & Handover Guide
// Synthesized by PM Agent in Phase 12
// Includes final Veritas report and known incomplete.
`;
        fs.writeFileSync(maintPath, content, 'utf8');
        console.log(`[PM] Generated MAINTENANCE_GUIDE.md at ${maintPath}`);
    }
}
